name: Python CI

on:
  push:
    branches:
      - "**"
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Start HTTP server on port 5000
        run: |
          nohup python3 -m http.server 5000 & # (THIS IS FOR TEST PURPOSES ONLY)
          sleep 2  # Give it time to start


      - name: Install & run tests in virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pytest --cov=src --cov-report=xml --cov-report=term --cov-fail-under=90